# Generated by Django 5.1.5 on 2025-02-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='posts',
            index=models.Index(fields=['-time_create'], name='cards_posts_time_cr_2c3ac2_idx'),
        ),
    ]
