# Generated by Django 5.1.5 on 2025-02-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_deck_posts_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='deck',
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
